import type { Metadata } from "next";
import { Cabin } from "next/font/google";
export const metadata: Metadata = {
  title: "Healbook: Your Personal Health Vault",
  description: "Generated by create next app",
};

const cabin = Cabin();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabin.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
